name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 3 * * *' # Runs once a day at 3 AM UTC
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://abhinavsarkar.net/all.atom"
          max_post_count: 10
          template: "$newline - <code>$date</code> [$title]($url) $categories"
          categories_template: "<code>$category</code>"
          date_format: "mmm dd yyyy"
